FROM randomcoww/kubernetes:base-v1.18.8 AS BASE

FROM scratch

COPY --from=BASE /usr/local/bin/kube-apiserver /usr/local/bin/
COPY --from=BASE /usr/local/bin/kube-controller-manager /usr/local/bin/
COPY --from=BASE /usr/local/bin/kube-scheduler /usr/local/bin/